version: '3'
services:
  ops:
    container_name: ops-frontend
    build: .
    ports:
      - "8083:8083"
    volumes:
      - .:/root/.ops/images/
  # redis:
  #   container_name: redis-backend
  #   image: "redis:alpine"
